[api_keys]
openai = "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"
langsmith = "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"