[browser]
gatherUsageStats = false

[server]
enableStaticServing = false
enableCORS = false

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[ui]
hideTopBar = true 